stages:
  - build

gcc:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles"
      -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++
      -DCMAKE_BUILD_TYPE=Release
      ..
    - cmake --build .

clang:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles"
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_BUILD_TYPE=Release
      ..
    - cmake --build .
